const { defineConfig } = require("cz-git");

module.exports = defineConfig({
  rules: {
    // @see: https://commitlint.js.org/#/reference-rules
  },
  prompt: {
    alias: { fd: "docs: fix typos" },
    messages: {
      type: "変更の種類を選択してください:",
      scope: "変更のスコープを入力してください（任意）:",
      customScope: "変更のスコープを入力してください:",
      subject: "変更内容を簡潔に記述してください:\n",
      body: '変更の詳細を記述してください（任意）。改行は"|"を使用:\n',
      breaking: '破壊的変更があれば記述してください（任意）。改行は"|"を使用:\n',
      footerPrefixesSelect:
        "この変更に関連するISSUEの種類を選択してください（任意）:",
      customFooterPrefix: "ISSUEプレフィックスを入力してください:",
      footer: "関連するISSUEを入力してください（例: #31, #34）:\n",
      generatingByAI: "AIがコミットメッセージを生成中...",
      generatedSelectByAI: "AIが生成したコミットメッセージを選択してください:",
      confirmCommit: "上記の内容でコミットしますか？",
    },
    types: [
      { value: "feat", name: "feat:     ✨ 新機能", emoji: "✨" },
      { value: "fix", name: "fix:      🐛 バグ修正", emoji: "🐛" },
      { value: "docs", name: "docs:     📝 ドキュメントのみの変更", emoji: "📝" },
      { value: "style", name: "style:    💄 コードの意味に影響しない変更", emoji: "💄" },
      { value: "refactor", name: "refactor: ♻️  リファクタリング", emoji: "♻️" },
      { value: "perf", name: "perf:     ⚡️ パフォーマンス改善", emoji: "⚡️" },
      { value: "test", name: "test:     ✅ テストの追加・修正", emoji: "✅" },
      { value: "build", name: "build:    📦️ ビルドシステム・外部依存の変更", emoji: "📦️" },
      { value: "ci", name: "ci:       🎡 CI設定の変更", emoji: "🎡" },
      { value: "chore", name: "chore:    🔨 その他の変更", emoji: "🔨" },
      { value: "revert", name: "revert:   ⏪️ コミットの取り消し", emoji: "⏪️" },
    ],
    useEmoji: true,
    emojiAlign: "center",
    useAI: false,
    aiNumber: 1,
    aiQuestionCB: ({ maxSubjectLength, diff }) =>
      `以下のgit diffに基づいて、${maxSubjectLength}文字以内の簡潔な日本語コミットメッセージを作成してください。絵文字は不要です:\n\`\`\`diff\n${diff}\n\`\`\``,
    themeColorCode: "",
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: "bottom",
    customScopesAlias: "custom",
    emptyScopesAlias: "empty",
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ["feat", "fix"],
    breaklineNumber: 100,
    breaklineChar: "|",
    skipQuestions: [],
    issuePrefixes: [
      { value: "closed", name: "closed:   ISSUEをクローズ" },
    ],
    customIssuePrefixAlign: "top",
    emptyIssuePrefixAlias: "skip",
    customIssuePrefixAlias: "custom",
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    scopeOverrides: undefined,
    defaultBody: "",
    defaultIssues: "",
    defaultScope: "",
    defaultSubject: "",
  },
});
